Use test reporter action

diff --git a/.github/workflows/dotnet-reusable-build.yml b/.github/workflows/dotnet-reusable-build.yml
--- a/.github/workflows/dotnet-reusable-build.yml
+++ b/.github/workflows/dotnet-reusable-build.yml
@@ -17,7 +17,7 @@ on:
           7.0.x
 
 jobs:
-  ci:
+  build:
     name: Build
     runs-on: ubuntu-latest
 
@@ -30,6 +30,26 @@ jobs:
       - name: Build
         working-directory: ${{inputs.working-directory}}
         run: dotnet build --configuration Release
+  
+  test:
+    name: Test
+    runs-on: ubuntu-latest
+    
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup .Net
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: ${{ inputs.dotnet-version }}
       - name: Test
         working-directory: ${{inputs.working-directory}}
-        run: dotnet test --configuration Release --no-build
+        run: dotnet test --logger "trx;LogFileName=test-results.trx" --configuration Release
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: .NET Tests            # Name of the check run which will be created
+          working-directory: ${{ inputs.working-directory }}
+          path: Tests/**/TestResults/*.trx    # Path to test results
+          reporter: dotnet-trx
+
